2021/08/15 22:50:09 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "OPTIONS /api/variables?limit=500 HTTP/1.1", upstream: "http://172.18.0.2:8529/_db/cenoteando/api/variables?limit=500", host: "localhost", referrer: "http://localhost:8080/"
2021/08/15 22:50:13 [error] 33#33: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "OPTIONS /api/cenotes/bounds HTTP/1.1", upstream: "http://172.18.0.2:8529/_db/cenoteando/api/cenotes/bounds", host: "localhost", referrer: "http://localhost:8080/"
2021/08/15 22:50:13 [error] 33#33: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "OPTIONS /api/cenotes HTTP/1.1", upstream: "http://172.18.0.2:8529/_db/cenoteando/api/cenotes", host: "localhost", referrer: "http://localhost:8080/"
2021/08/15 22:50:30 [error] 33#33: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "OPTIONS /api/variables?limit=500 HTTP/1.1", upstream: "http://172.18.0.2:8529/_db/cenoteando/api/variables?limit=500", host: "localhost", referrer: "http://localhost:8080/"
