2021/09/20 14:12:25 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "OPTIONS /api/auth/register HTTP/1.1", upstream: "http://172.19.0.2:8529/_db/cenoteando/api/auth/register", host: "localhost", referrer: "http://localhost:8080/"
