2021/10/17 14:54:52 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "OPTIONS /api/auth/login HTTP/1.1", upstream: "http://172.18.0.2:8529/_db/cenoteando/api/auth/login", host: "localhost", referrer: "http://localhost:8080/"
2021/10/26 10:31:25 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /api/cenotes/bounds HTTP/1.1", upstream: "http://172.19.0.2:8529/_db/cenoteando/api/cenotes/bounds", host: "localhost", referrer: "http://localhost:8080/"
2021/10/26 10:31:25 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /api/cenotes HTTP/1.1", upstream: "http://172.19.0.2:8529/_db/cenoteando/api/cenotes", host: "localhost", referrer: "http://localhost:8080/"
2021/10/26 10:31:51 [error] 32#32: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "OPTIONS /api/auth/register HTTP/1.1", upstream: "http://172.19.0.2:8529/_db/cenoteando/api/auth/register", host: "localhost", referrer: "http://localhost:8080/"
2021/10/26 10:31:53 [error] 32#32: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "OPTIONS /api/auth/register HTTP/1.1", upstream: "http://172.19.0.2:8529/_db/cenoteando/api/auth/register", host: "localhost", referrer: "http://localhost:8080/"
